export const politicalData = [
    {
        "Candidate": "CHARLES HUGHES",
        "Title": "Small Business Owner",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "9889 ELIZABETH LAKE RD",
        "City": "LEONA VALLEY",
        "State": "CA",
        "ZipCode": 93551.0,
        "Email": "chcrazyottos@gmail.com",
        "Website": null,
        "Phone": "(661) 492-1790",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "MICHELLE ROYAL",
        "Title": "Business Owner Entrepreneur",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "9549 NORTHSIDE DR",
        "City": "LEONA VALLEY",
        "State": "CA",
        "ZipCode": 93551.0,
        "Email": "michelle@dpcommercial.com",
        "Website": null,
        "Phone": "(661) 917-0917",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "CARLO BASAIL",
        "Title": "Member, County Central Committee",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "33154 AGUA DULCE CYN RD",
        "City": "AGUA DULCE",
        "State": "CA",
        "ZipCode": 91390.0,
        "Email": "carlobasail@yahoo.com",
        "Website": null,
        "Phone": "(661) 713-6123",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "DREW MERCY",
        "Title": "Member, County Central Committee",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "43759 15TH ST W, PMB 36",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": 93534.0,
        "Email": "drew@drewmercy.com",
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "JAMES ROYAL",
        "Title": "Transportation Executive",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "9549 NORTHSIDE DR",
        "City": "LEONA VALLEY",
        "State": "CA",
        "ZipCode": 93551.0,
        "Email": "james.royal.plus@gmail.com",
        "Website": null,
        "Phone": "(818) 279-3384",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "JACK DANIELSON",
        "Title": "Taxpayer Advocate Educator",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "7362 SANDPIPER DR",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": "93536-7331",
        "Email": "jackdanielson99@gmail.com",
        "Website": null,
        "Phone": "(661) 900-8921",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "RAJ MALHI",
        "Title": "Member, County Central Committee",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "34th District",
        "Address": "2007 W AVE J",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": 93534.0,
        "Email": "rajmalhi21@gmail.com",
        "Website": null,
        "Phone": "(661) 305-5888",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "DEBORAH DINO",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": "37640 GRANT CT",
        "City": "PALMDALE",
        "State": "CA",
        "ZipCode": 93552.0,
        "Email": "debino53@yahoo.com",
        "Website": null,
        "Phone": "(661) 435-1188",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "KAREN ROSEBERRY",
        "Title": "Non-Profit Executive Director",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": "40107 173RD ST EAST",
        "City": "PALMDALE",
        "State": "CA",
        "ZipCode": 93591.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "BRYAN ANGUIANO",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": "1814 W AVENUE J15 #5",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": 93534.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "KENNETH MANN",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "ARCADIA VENEGAS",
        "Title": "Small Business Owner",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "MARVIN CRIST",
        "Title": "Member, County Central Committee",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": "1321 W LANCASTER BLVD",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": 93634.0,
        "Email": "marvin.e.crist@gmail.com",
        "Website": null,
        "Phone": "(661) 917-0126",
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "VINCENT J. DINO",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "39th District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/1/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "DANIEL MALDONADO",
        "Title": "Businessman",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "24355 CREEKSIDE RD #802072",
        "City": "SANTA CLARITA",
        "State": "CA",
        "ZipCode": 91355.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "11/29/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "NUNE GIPSON",
        "Title": "Businesswoman Paralegal Mom",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "263 W OLIVE AVE #364",
        "City": "BURBANK",
        "State": "CA",
        "ZipCode": 91502.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "11/16/2023 "
    },
    {
        "Candidate": "MELISSA LUNDIE",
        "Title": "Small Business Owner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "P O BOX 802072",
        "City": "SANTA CLARITA",
        "State": "CA",
        "ZipCode": 91355.0,
        "Email": "melissalundie@gmail.com",
        "Website": null,
        "Phone": "(805) 748-1444",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "11/29/2023 "
    },
    {
        "Candidate": "VERONICA HIXSON",
        "Title": "Educator Parent",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "P O BOX 802072",
        "City": "SANTA CLARITA",
        "State": "CA",
        "ZipCode": 91355.0,
        "Email": "vhixson73@gmail.com",
        "Website": null,
        "Phone": "(661) 212-5038",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "11/22/2023 "
    },
    {
        "Candidate": "LUCIE VOLOTZKY",
        "Title": "Mother Businesswoman",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "21704 DEVONSHIRE ST # 255",
        "City": "CHATSWORTH",
        "State": "CA",
        "ZipCode": 91311.0,
        "Email": null,
        "Website": "www.voteforlucie.com",
        "Phone": "(747) 285-0803",
        "NOMIssueDate": "11/21/2023 ",
        "NOMFileDate": "11/30/2023 "
    },
    {
        "Candidate": "JOE MESSINA",
        "Title": null,
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "26893 BOUQUET CYN STE C336",
        "City": "SANTA CLARITA",
        "State": "CA",
        "ZipCode": 91350.0,
        "Email": "joe@joemessina.com",
        "Website": null,
        "Phone": "(661) 257-9250",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "PATRICK GIPSON",
        "Title": "Retired Deputy Sheriff",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "20259 BENTLEY WAY",
        "City": "PORTER RANCH",
        "State": "CA",
        "ZipCode": 91326.0,
        "Email": "patrick@gipson4assembly.com",
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/7/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "AAKASH AHUJA",
        "Title": "Doctor",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "28404 STEEL LN",
        "City": "VALENCIA",
        "State": "CA",
        "ZipCode": 91354.0,
        "Email": "dr.aakash2020@gmail.com",
        "Website": null,
        "Phone": "(612) 201-3488",
        "NOMIssueDate": "11/8/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "JUDY LAMPPU",
        "Title": "Writer",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "20121 VENTURA BLVD #307",
        "City": "WOODLAND HILLS",
        "State": "CA",
        "ZipCode": 91364.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/16/2023 ",
        "NOMFileDate": "11/14/2023 "
    },
    {
        "Candidate": "DENISE LITE",
        "Title": "Attorney Parent Entrepreneur",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "40th District",
        "Address": "21649 PARVIN DR",
        "City": "SANTA CLARITA",
        "State": "CA",
        "ZipCode": 91350.0,
        "Email": "dplacencio@dacorsi.net",
        "Website": null,
        "Phone": "(818) 522-6482",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "BONNIE WALLACE",
        "Title": "Educator Community Organizer",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": "bonbonmom@gmail.com",
        "Website": null,
        "Phone": "(626) 644-4845",
        "NOMIssueDate": "10/3/2023 ",
        "NOMFileDate": "12/1/2023 "
    },
    {
        "Candidate": "JACK C. MERCICA",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/3/2023 ",
        "NOMFileDate": "10/30/2023 "
    },
    {
        "Candidate": "LOIS BRAND BILLINGS",
        "Title": "Educator Realtor Businessowner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": "loisleeb@aol.com",
        "Website": null,
        "Phone": "(626) 823-4679",
        "NOMIssueDate": "12/4/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "JACQUELINE MUNOZ",
        "Title": "Realtor Non-Profit Coordinator",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/23/2023 ",
        "NOMFileDate": "11/3/2023 "
    },
    {
        "Candidate": "DEBORAH SCOTT TOUX",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/5/2023 ",
        "NOMFileDate": "11/6/2023 "
    },
    {
        "Candidate": "PIERRE SYLLA",
        "Title": null,
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/23/2023 ",
        "NOMFileDate": "11/1/2023 "
    },
    {
        "Candidate": "CALLIE GREGORY",
        "Title": "Appointed Member County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/5/2023 ",
        "NOMFileDate": "11/6/2023 "
    },
    {
        "Candidate": "CYNTHIA GABALDON",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "41st District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": "(909) 455-8520",
        "NOMIssueDate": "10/5/2023 ",
        "NOMFileDate": "11/6/2023 "
    },
    {
        "Candidate": "LEO SAMUEL ZACKY",
        "Title": "Farmer Businessman Broadcaster",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "149 S BARRINGTON AVE #720",
        "City": "LOS ANGELES",
        "State": "CA",
        "ZipCode": 90049.0,
        "Email": "leo@leoszacky.com",
        "Website": "www.leozacky.com",
        "Phone": "(310) 357-5167",
        "NOMIssueDate": "12/5/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "RICHARD MULLEN",
        "Title": "Fire Captain",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/10/2023 ",
        "NOMFileDate": "12/4/2023 "
    },
    {
        "Candidate": "RONNIE BANSBACH",
        "Title": "Homemaker",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/18/2023 ",
        "NOMFileDate": "12/6/2023 "
    },
    {
        "Candidate": "ELIZABETH BARCOHANA",
        "Title": "Mother Attorney",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "11/29/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "GINGER HYDE",
        "Title": "Small Business Owner",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "528 PALISADES DR #140",
        "City": "PACIFIC PALISADES",
        "State": "CA",
        "ZipCode": 90272.0,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "10/6/2023 ",
        "NOMFileDate": "12/1/2023 "
    },
    {
        "Candidate": "CLIFTON RIO TORRADO VON BUCK",
        "Title": "Business Owner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "2010 WEST AVE K #522",
        "City": "LANCASTER",
        "State": "CA",
        "ZipCode": 93536.0,
        "Email": "junkvb@att.net",
        "Website": null,
        "Phone": "(620) 207-1843",
        "NOMIssueDate": "11/30/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "KAREN SIEGEMUND",
        "Title": "Member, County Central Committee",
        "Status": "E",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "4263 LAS VIRGENES RD UNIT 4",
        "City": "CALABASAS",
        "State": "CA",
        "ZipCode": 91302.0,
        "Email": "kwsiegemund@aol.com",
        "Website": null,
        "Phone": "(401) 965-9440",
        "NOMIssueDate": "11/6/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "MARIANNE RIGGINS",
        "Title": "Retired City Employee",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": null,
        "City": null,
        "State": null,
        "ZipCode": null,
        "Email": null,
        "Website": null,
        "Phone": null,
        "NOMIssueDate": "12/4/2023 ",
        "NOMFileDate": "12/6/2023 "
    },
    {
        "Candidate": "DENIS WEBER",
        "Title": "Retired Local Banker",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "6340 GERMANIA CT",
        "City": "AGOURA HILLS",
        "State": "CA",
        "ZipCode": 91301.0,
        "Email": null,
        "Website": null,
        "Phone": "(818) 317-8151",
        "NOMIssueDate": "11/27/2023 ",
        "NOMFileDate": "12/4/2023 "
    },
    {
        "Candidate": "K. \"KEVIN\" HEDVAT",
        "Title": null,
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "9775 PEAVINE DR",
        "City": "BEVERLY HILLS",
        "State": "CA",
        "ZipCode": 90210.0,
        "Email": "kevin@hedvat.com",
        "Website": null,
        "Phone": "(310) 741-0485",
        "NOMIssueDate": "10/16/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "MARSHALL MULLEN",
        "Title": "Small Business Owner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "42nd District",
        "Address": "5969 RAMIREZ CANYON RD",
        "City": "MALIBU",
        "State": "CA",
        "ZipCode": 90265.0,
        "Email": "marshallmullen@gmail.com",
        "Website": null,
        "Phone": "(310) 924-4316",
        "NOMIssueDate": "11/27/2023 ",
        "NOMFileDate": "12/4/2023 "
    },
    {
        "Candidate": "SIAKA MASSAQUOI",
        "Title": "Producer",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "7029 BELLAIRE AVE",
        "City": "NORTH HOLLYWOOD",
        "State": "CA",
        "ZipCode": 91605.0,
        "Email": "siakamassaquoi@gmail.com",
        "Website": null,
        "Phone": "(310) 750-7362",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "12/8/2023 "
    },
    {
        "Candidate": "ROXANNE HOGE",
        "Title": "Appointed Member, County Central Committee",
        "Status": "A",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "4804 LAUREL CANYON BLVD #369",
        "City": "VALLEY VILLAGE",
        "State": "CA",
        "ZipCode": 91607.0,
        "Email": "roxannehoge@gmail.com",
        "Website": "www.roxannebeckford.com",
        "Phone": "(818) 650-0466",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "12/7/2023 "
    },
    {
        "Candidate": "FELICIA L. NOVICK",
        "Title": "Mom Office Administrator",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "6633 WOODMAN AVE #7",
        "City": "VAN NUYS",
        "State": "CA",
        "ZipCode": 91401.0,
        "Email": null,
        "Website": null,
        "Phone": "(310) 902-7223",
        "NOMIssueDate": "10/10/2023 ",
        "NOMFileDate": "11/2/2023 "
    },
    {
        "Candidate": "OTTO KRAUSE",
        "Title": "Small Business Owner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "7833 RHODES AVE",
        "City": "NORTH HOLLYWOOD",
        "State": "CA",
        "ZipCode": 91605.0,
        "Email": "ottobkrause@gmail.com",
        "Website": null,
        "Phone": "(310) 713-6886",
        "NOMIssueDate": "10/25/2023 ",
        "NOMFileDate": "11/27/2023 "
    },
    {
        "Candidate": "MAHEALANI KANE URQUIZA",
        "Title": "Veteran Community Advocate",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "14739 ARARAT ST",
        "City": "SYLMAR",
        "State": "CA",
        "ZipCode": 91342.0,
        "Email": "kane.lani66@gmail.com",
        "Website": null,
        "Phone": "(707) 349-5457",
        "NOMIssueDate": "10/27/2023 ",
        "NOMFileDate": "11/30/2023 "
    },
    {
        "Candidate": "AUDREY BARANISHYN-KRAUSE",
        "Title": "Small Business Owner",
        "Status": "N",
        "Party": "Republican ",
        "Office": "MEMBER, COUNTY CENTRAL COMMITTEE",
        "District": "43rd District",
        "Address": "7833 RHODES AVE",
        "City": "NORTH HOLLYWOOD",
        "State": "CA",
        "ZipCode": 91605.0,
        "Email": "kineticonnection@gmail.com",
        "Website": null,
        "Phone": "(818) 427-8835",
        "NOMIssueDate": "10/25/2023 ",
        "NOMFileDate": "11/27/2023 "
    }
]