export const politicalData = [
    {
      id: 1,
      Candidate: 'CHARLES HUGHES',
      Title: 'Small Business Owner',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '9889 ELIZABETH LAKE RD',
      City: 'LEONA VALLEY',
      State: 'State A',
      ZipCode: 93551,
      Email: 'chcrazyottos@gmail.com',
      Website: null,
      Phone: '(661) 492-1790',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 2,
      Candidate: 'MICHELLE ROYAL',
      Title: 'Business Owner/Entrepreneur',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '9549 NORTHSIDE DR',
      City: 'LEONA VALLEY',
      State: 'State A',
      ZipCode: 93551,
      Email: 'michelle@dpcommercial.com',
      Website: null,
      Phone: '(661) 917-0917',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id:3,
      Candidate: 'CARLO BASAIL',
      Title: 'Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '33154 AGUA DULCE CYN RD',
      City: 'AGUA DULCE',
      State: 'State A',
      ZipCode: 91390,
      Email: 'carlobasail@yahoo.com',
      Website: null,
      Phone: '(661) 713-6123',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 4,
      Candidate: 'DREW MERCY',
      Title: 'Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '43759 15TH ST W, PMB 36',
      City: 'LANCASTER',
      State: 'State A',
      ZipCode: 93534,
      Email: 'drew@drewmercy.com',
      Website: null,
      Phone: null,
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 5,
      Candidate: 'JAMES ROYAL',
      Title: 'Transportation Executive',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '9549 NORTHSIDE DR',
      City: 'LEONA VALLEY',
      State: 'State A',
      ZipCode: 93551,
      Email: 'james.royal.plus@gmail.com',
      Website: null,
      Phone: '(818) 279-3384',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 6,
      Candidate: 'JACK DANIELSON',
      Title: 'Taxpayer Advocate/Educator',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '7362 SANDPIPER DR',
      City: 'LANCASTER',
      State: 'State A',
      ZipCode: '93536-7331',
      Email: 'jackdanielson99@gmail.com',
      Website: null,
      Phone: '(661) 900-8921',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 7,
      Candidate: 'RAJ MALHI',
      Title: 'Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '34th District',
      Address: '2007 W AVE J',
      City: 'LANCASTER',
      State: 'State A',
      ZipCode: 93534,
      Email: 'rajmalhi21@gmail.com',
      Website: null,
      Phone: '(661) 305-5888',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 8,
      Candidate: 'DEBORAH DINO',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: '37640 GRANT CT',
      City: 'PALMDALE',
      State: 'State A',
      ZipCode: 93552,
      Email: 'debino53@yahoo.com',
      Website: null,
      Phone: '(661) 435-1188',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 9,
      Candidate: 'KAREN ROSEBERRY',
      Title: 'Non-Profit Executive Director',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: '40107 173RD ST EAST',
      City: 'PALMDALE',
      State: 'State A',
      ZipCode: 93591,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 10,
      Candidate: 'BRYAN ANGUIANO',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: '1814 W AVENUE J15 #5',
      City: 'LANCASTER',
      State: 'State A',
      ZipCode: 93534,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 11,
      Candidate: 'KENNETH MANN',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: null,
      City: null,
      State: 'State A',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 12,
      Candidate: 'ARCADIA VENEGAS',
      Title: 'Small Business Owner',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: null,
      City: null,
      State: 'State A',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 13,
      Candidate: 'MARVIN CRIST',
      Title: 'Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: '1321 W LANCASTER BLVD',
      City: 'LANCASTER',
      State: 'State B',
      ZipCode: 93634,
      Email: 'marvin.e.crist@gmail.com',
      Website: null,
      Phone: '(661) 917-0126',
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 14,
      Candidate: 'VINCENT J. DINO',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '39th District',
      Address: null,
      City: null,
      State: 'State B',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '12/1/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 15,
      Candidate: 'DANIEL MALDONADO',
      Title: 'Businessman',
      Status: 'Incumbent',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '24355 CREEKSIDE RD #802072',
      City: 'SANTA CLARITA',
      State: 'State B',
      ZipCode: 91355,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '11/29/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 16,
      Candidate: 'NUNE GIPSON',
      Title: 'Businesswoman/Paralegal/Mom',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '263 W OLIVE AVE #364',
      City: 'BURBANK',
      State: 'State B',
      ZipCode: 91502,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '11/16/2023 '
    },
    {
      id: 17,
      Candidate: 'MELISSA LUNDIE',
      Title: 'Small Business Owner',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: 'P O BOX 802072',
      City: 'SANTA CLARITA',
      State: 'State B',
      ZipCode: 91355,
      Email: 'melissalundie@gmail.com',
      Website: null,
      Phone: '(805) 748-1444',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '11/29/2023 '
    },
    {
      id: 18,
      Candidate: 'VERONICA HIXSON',
      Title: 'Educator/Parent',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: 'P O BOX 802072',
      City: 'SANTA CLARITA',
      State: 'State B',
      ZipCode: 91355,
      Email: 'vhixson73@gmail.com',
      Website: null,
      Phone: '(661) 212-5038',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '11/22/2023 '
    },
    {
      id: 19,
      Candidate: 'LUCIE VOLOTZKY',
      Title: 'Mother/Businesswoman',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '21704 DEVONSHIRE ST # 255',
      City: 'CHATSWORTH',
      State: 'State B',
      ZipCode: 91311,
      Email: null,
      Website: 'www.voteforlucie.com',
      Phone: '(747) 285-0803',
      NOMIssueDate: '11/21/2023 ',
      NOMFileDate: '11/30/2023 '
    },
    {
      id: 20,
      Candidate: 'JOE MESSINA',
      Title: null,
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '26893 BOUQUET CYN STE C336',
      City: 'SANTA CLARITA',
      State: 'State B',
      ZipCode: 91350,
      Email: 'joe@joemessina.com',
      Website: null,
      Phone: '(661) 257-9250',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 21,
      Candidate: 'PATRICK GIPSON',
      Title: 'Retired Deputy Sheriff',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '20259 BENTLEY WAY',
      City: 'PORTER RANCH',
      State: 'State B',
      ZipCode: 91326,
      Email: 'patrick@gipson4assembly.com',
      Website: null,
      Phone: null,
      NOMIssueDate: '12/7/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 22,
      Candidate: 'AAKASH AHUJA',
      Title: 'Doctor',
      Status: 'Challenger',
      Party: 'Democrat',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '28404 STEEL LN',
      City: 'VALENCIA',
      State: 'State B',
      ZipCode: 91354,
      Email: 'dr.aakash2020@gmail.com',
      Website: null,
      Phone: '(612) 201-3488',
      NOMIssueDate: '11/8/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 23,
      Candidate: 'JUDY LAMPPU',
      Title: 'Writer',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '20121 VENTURA BLVD #307',
      City: 'WOODLAND HILLS',
      State: 'State C',
      ZipCode: 91364,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/16/2023 ',
      NOMFileDate: '11/14/2023 '
    },
    {
      id: 24,
      Candidate: 'DENISE LITE',
      Title: 'Attorney/Parent/Entrepreneur',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '40th District',
      Address: '21649 PARVIN DR',
      City: 'SANTA CLARITA',
      State: 'State C',
      ZipCode: 91350,
      Email: 'dplacencio@dacorsi.net',
      Website: null,
      Phone: '(818) 522-6482',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 25,
      Candidate: 'BONNIE WALLACE',
      Title: 'Educator/Community Organizer',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: 'bonbonmom@gmail.com',
      Website: null,
      Phone: '(626) 644-4845',
      NOMIssueDate: '10/3/2023 ',
      NOMFileDate: '12/1/2023 '
    },
    {
      id:26,
      Candidate: 'JACK C. MERCICA',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/3/2023 ',
      NOMFileDate: '10/30/2023 '
    },
    {
      id: 27,
      Candidate: 'LOIS BRAND BILLINGS',
      Title: 'Educator/Realtor/Businessowner',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: 'loisleeb@aol.com',
      Website: null,
      Phone: '(626) 823-4679',
      NOMIssueDate: '12/4/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 28,
      Candidate: 'JACQUELINE MUNOZ',
      Title: 'Realtor/Non-Profit Coordinator',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/23/2023 ',
      NOMFileDate: '11/3/2023 '
    },
    {
      id: 29,
      Candidate: 'DEBORAH SCOTT TOUX',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/5/2023 ',
      NOMFileDate: '11/6/2023 '
    },
    {
      id: 30,
      Candidate: 'PIERRE SYLLA',
      Title: null,
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/23/2023 ',
      NOMFileDate: '11/1/2023 '
    },
    {
      id: 31,
      Candidate: 'CALLIE GREGORY',
      Title: 'Appointed Member County Central Committee',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/5/2023 ',
      NOMFileDate: '11/6/2023 '
    },
    {
      id: 32,
      Candidate: 'CYNTHIA GABALDON',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '41st District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: '(909) 455-8520',
      NOMIssueDate: '10/5/2023 ',
      NOMFileDate: '11/6/2023 '
    },
    {
      id: 33,
      Candidate: 'LEO SAMUEL ZACKY',
      Title: 'Farmer/Businessman/Broadcaster',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '149 S BARRINGTON AVE #720',
      City: 'LOS ANGELES',
      State: 'State C',
      ZipCode: 90049,
      Email: 'leo@leoszacky.com',
      Website: 'www.leozacky.com',
      Phone: '(310) 357-5167',
      NOMIssueDate: '12/5/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 34,
      Candidate: 'RICHARD MULLEN',
      Title: 'Fire Captain',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/10/2023 ',
      NOMFileDate: '12/4/2023 '
    },
    {
      id: 35,
      Candidate: 'RONNIE BANSBACH',
      Title: 'Homemaker',
      Status: 'Challenger',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/18/2023 ',
      NOMFileDate: '12/6/2023 '
    },
    {
      id: 36,
      Candidate: 'ELIZABETH BARCOHANA',
      Title: 'Mother/Attorney',
      Status: 'Open Seat',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: null,
      City: null,
      State: 'State C',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '11/29/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 37,
      Candidate: 'GINGER HYDE',
      Title: 'Small Business Owner',
      Status: 'Open Seat',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '528 PALISADES DR #140',
      City: 'PACIFIC PALISADES',
      State: 'State C',
      ZipCode: 90272,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '10/6/2023 ',
      NOMFileDate: '12/1/2023 '
    },
    {
      id: 38,
      Candidate: 'CLIFTON RIO TORRADO VON BUCK',
      Title: 'Business Owner',
      Status: 'Open Seat',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '2010 WEST AVE K #522',
      City: 'LANCASTER',
      State: 'State D',
      ZipCode: 93536,
      Email: 'junkvb@att.net',
      Website: null,
      Phone: '(620) 207-1843',
      NOMIssueDate: '11/30/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 39,
      Candidate: 'KAREN SIEGEMUND',
      Title: 'Member, County Central Committee',
      Status: 'Open Seat',
      Party: 'Republican',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '4263 LAS VIRGENES RD UNIT 4',
      City: 'CALABASAS',
      State: 'State D',
      ZipCode: 91302,
      Email: 'kwsiegemund@aol.com',
      Website: null,
      Phone: '(401) 965-9440',
      NOMIssueDate: '11/6/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 40,
      Candidate: 'MARIANNE RIGGINS',
      Title: 'Retired City Employee',
      Status: 'Open Seat',
      Party: 'Independent',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: null,
      City: null,
      State: 'State D',
      ZipCode: null,
      Email: null,
      Website: null,
      Phone: null,
      NOMIssueDate: '12/4/2023 ',
      NOMFileDate: '12/6/2023 '
    },
    {
      id: 41,
      Candidate: 'DENIS WEBER',
      Title: 'Retired Local Banker',
      Status: 'Open Seat',
      Party: 'Independent',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '6340 GERMANIA CT',
      City: 'AGOURA HILLS',
      State: 'State D',
      ZipCode: 91301,
      Email: null,
      Website: null,
      Phone: '(818) 317-8151',
      NOMIssueDate: '11/27/2023 ',
      NOMFileDate: '12/4/2023 '
    },
    {
      id: 42,
      Candidate: 'K. "KEVIN" HEDVAT',
      Title: null,
      Status: 'Open Seat',
      Party: 'Independent',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '9775 PEAVINE DR',
      City: 'BEVERLY HILLS',
      State: 'State D',
      ZipCode: 90210,
      Email: 'kevin@hedvat.com',
      Website: null,
      Phone: '(310) 741-0485',
      NOMIssueDate: '10/16/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 43,
      Candidate: 'MARSHALL MULLEN',
      Title: 'Small Business Owner',
      Status: 'Open Seat',
      Party: 'Independent',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '42nd District',
      Address: '5969 RAMIREZ CANYON RD',
      City: 'MALIBU',
      State: 'State D',
      ZipCode: 90265,
      Email: 'marshallmullen@gmail.com',
      Website: null,
      Phone: '(310) 924-4316',
      NOMIssueDate: '11/27/2023 ',
      NOMFileDate: '12/4/2023 '
    },
    {
      id: 44,
      Candidate: 'SIAKA MASSAQUOI',
      Title: 'Producer',
      Status: 'Open Seat',
      Party: 'Independent',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '7029 BELLAIRE AVE',
      City: 'NORTH HOLLYWOOD',
      State: 'State D',
      ZipCode: 91605,
      Email: 'siakamassaquoi@gmail.com',
      Website: null,
      Phone: '(310) 750-7362',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '12/8/2023 '
    },
    {
      id: 45,
      Candidate: 'ROXANNE HOGE',
      Title: 'Appointed Member, County Central Committee',
      Status: 'Open Seat',
      Party: 'Other',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '4804 LAUREL CANYON BLVD #369',
      City: 'VALLEY VILLAGE',
      State: 'State D',
      ZipCode: 91607,
      Email: 'roxannehoge@gmail.com',
      Website: 'www.roxannebeckford.com',
      Phone: '(818) 650-0466',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '12/7/2023 '
    },
    {
      id: 46,
      Candidate: 'FELICIA L. NOVICK',
      Title: 'Mom/Office Administrator',
      Status: 'Write-in Candidate',
      Party: 'Other',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '6633 WOODMAN AVE #7',
      City: 'VAN NUYS',
      State: 'State D',
      ZipCode: 91401,
      Email: null,
      Website: null,
      Phone: '(310) 902-7223',
      NOMIssueDate: '10/10/2023 ',
      NOMFileDate: '11/2/2023 '
    },
    {
      id: 47,
      Candidate: 'OTTO KRAUSE',
      Title: 'Small Business Owner',
      Status: 'Write-in Candidate',
      Party: 'Other',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '7833 RHODES AVE',
      City: 'NORTH HOLLYWOOD',
      State: 'State D',
      ZipCode: 91605,
      Email: 'ottobkrause@gmail.com',
      Website: null,
      Phone: '(310) 713-6886',
      NOMIssueDate: '10/25/2023 ',
      NOMFileDate: '11/27/2023 '
    },
    {
      id: 48,
      Candidate: 'MAHEALANI KANE URQUIZA',
      Title: 'Veteran Community Advocate',
      Status: 'Write-in Candidate',
      Party: 'Other',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '14739 ARARAT ST',
      City: 'SYLMAR',
      State: 'State D',
      ZipCode: 91342,
      Email: 'kane.lani66@gmail.com',
      Website: null,
      Phone: '(707) 349-5457',
      NOMIssueDate: '10/27/2023 ',
      NOMFileDate: '11/30/2023 '
    },
    {
      id: 49,
      Candidate: 'AUDREY BARANISHYN-KRAUSE',
      Title: 'Small Business Owner',
      Status: 'Write-in Candidate',
      Party: 'Other',
      Office: 'MEMBER, COUNTY CENTRAL COMMITTEE',
      District: '43rd District',
      Address: '7833 RHODES AVE',
      City: 'NORTH HOLLYWOOD',
      State: 'State D',
      ZipCode: 91605,
      Email: 'kineticonnection@gmail.com',
      Website: null,
      Phone: '(818) 427-8835',
      NOMIssueDate: '10/25/2023 ',
      NOMFileDate: '11/27/2023 '
    }
  ]